{
 "title": "OSM Project Status - OSM_NAME",
 "tags": [ "osm_automated" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "project_id", "label": "Project ID", "query": "OSM_ID" }
  ]
 },
 "panels": [
  {
   "title": "VIM Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "osm_vim_status{project_id=\"$project_id\"}",
     "legendFormat": "{{vim_account_id}}"
    }
   ]
  },
  {
   "title": "SDN Controller Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "osm_sdnc_status{project_id=\"$project_id\"}",
     "legendFormat": "{{sdnc_id}}"
    }
   ]
  },
  {
   "title": "Network Services",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "count(max(osm_vm_status{project_id=\"$project_id\"}) by (ns_name))"
    }
   ]
  },
  {
   "title": "VDUs per NS",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "count(osm_vm_status{project_id=\"$project_id\"}) by (ns_name)",
     "legendFormat": "NS {{nsr_id}}"
    }
   ]
  },
  {
   "title": "Network Service Status (based on VM State)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "min(osm_vm_status{project_id=\"$project_id\"}) by (ns_name)",
     "legendFormat": "NS {{nsr_id}} - VNF {{vnf_member_index}} - VDU {{vdur_name}}"
    }
   ]
  },
  {
   "title": "VDU Status over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Status" }
   ],
   "targets": [
    {
     "expr": "osm_vm_status{project_id=\"$project_id\"}",
     "legendFormat": "{{nsr_id}} - {{vdur_name}}"
    }
   ]
  }
 ]
}